#' Significant earthquakes around the world
#'
#'   This dataset contains information about 5,933 earthquakes over
#'   an approximately 4,000 year time span.
#'
#'   @source Dataset NOAA Significant Earthquake Database
#'   \url{https://www.ngdc.noaa.gov/nndc/struts/form?t=101650&s=1&d=1}
#'   National Geophysical Data Center / World Data Service (NGDC / WDS):
#'   Significant Earthquake Database.
#'   National Geophysical Data Center, NOAA. doi:10.7289 / V5TD9V7K
#'
#'   @format A data frame with columns:
#'   \describe{
#'   \item{I_D}{The unique numeric identifier of the record. }
#'   \item{FLAG_TSUNAMI}{When a tsunami was generated by an earthquake, "Tsu" appear.}
#'   \item{YEAR}{Year: Format +/-yyyy (-is B.C, +is A.D.)}
#'   \item{MONTH}{Month: 1-12}
#'   \item{DAY}{Day: 1-31 (where months apply)}
#'   \item{HOUR}{Hour: 0-23}
#'   \item{MINUTE}{Minute:  0-59}
#'   \item{SECOND}{Second: 0-59}
#'   \item{FOCAL_DEPTH}{The depth of the earthquake is given in kilometers.}
#'   \item{EQ_PRIMARY}{Magnitude: 0.0 to 9.9}
#'   \item{EQ_MAG_MW}{The Mw magnitude is based on the moment magnitude scale.}
#'   \item{EQ_MAG_MS}{The Ms magnitude is the surface-wave magnitude of the earthquake.}
#'   \item{EQ_MAG_MB}{The Mb magnitude is the compressional body wave (P-wave) magnitude.}
#'   \item{EQ_MAG_ML}{The ML magnitude was the original magnitude relationship defined by Richter and Gutenberg for local earthquakes in 1935.}
#'   \item{EQ_MAG_MFA}{The Mfa magnitudes are computed from the felt area, for earthquakes that occurred before seismic instruments were in general use.}
#'   \item{EQ_MAG_UNK}{The computational method for the earthquake magnitude was unknown and could not be determined from the published sources.}
#'   \item{INTENSITY}{The Modified Mercalli Intensity (Int) is given in Roman Numerals (converted to numbers in the digital database). 1-12}
#'   \item{COUNTRY}{The Country where the Earthquake occurred.}
#'   \item{STATE}{The two-letter State or Province abbreviation where the Earthquake occurred.}
#'   \item{LOCATION_NAME}{The State, Province or City where the Earthquake occurred }
#'   \item{LATITUDE}{Latitude: 0 to 90 (Northern Hemisphere) -90 to 0 (Southern Hemisphere)}
#'   \item{LONGITUDE}{Longitude: 0 to 180 (Eastern Hemisphere) -180 to 0 (Western Hemisphere)}
#'   \item{REGION_CODE}{Regional boundaries defined as follows:
#'   10 = Central, Western and S. Africa
#'   15 = Northern Africa
#'   20 = Antarctica
#'   30 = East Asia
#'   40 = Central Asia and Caucasus
#'   50 = Kamchatka and Kuril Islands
#'   60 = S. and SE. Asia and Indian Ocean
#'   70 = Atlantic Ocean
#'   80 = Bering Sea
#'   90 = Caribbean
#'   100 = Central America
#'   110 = Eastern Europe
#'   120 = Northern and Western Europe
#'   130 = Southern Europe
#'   140 = Middle East
#'   150 = North America and Hawaii
#'   160 = South America
#'   170 = Central and South Pacific
#'   }
#'   \item{DEATHS}{Number of Deaths from the Earthquake}
#'   \item{DEATHS_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 deaths)
#'   2 = Some (~51 to 100 deaths)
#'   3 = Many (~101 to 1000 deaths)
#'   4 = Very Many (~1001 or more deaths)
#'   }
#'   \item{MISSING}{Number of Missing from the Earthquake}
#'   \item{MISSING_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 missing)
#'   2 = Some(~51 to 100 missing)
#'   3 = Many (~101 to 1000 missing)
#'   4 = Very Many (~1001 or more missing)
#'   }
#'   \item{INJURIES}{Number of Injuries from the Earthquake}
#'   \item{INJURIES_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 injuries)
#'   2 = Some(~51 to 100 injuries)
#'   3 = Many (~101 to 1000 injuries)
#'   4 = Very Many (~1001 or more injuries)
#'   }
#'   \item{DAMAGE_MILLIONS_DOLLARS}{Damage in Millions of Dollars from the Earthquake.}
#'   \item{DAMAGE_DESCRIPTION}{
#'   0 = NONE
#'   1 = LIMITED (roughly corresponding to less than $1 million)
#'   2 = MODERATE (~$1 to $5 million)
#'   3 = SEVERE (~>$5 to $24 million)
#'   4 = EXTREME (~$25 million or more)
#'   }
#'   \item{HOUSES_DESTROYED}{Total Number of Houses Destroyed by the Earthquake.}
#'   \item{HOUSES_DESTROYED_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 houses)
#'   2 = Some (~51 to 100 houses)
#'   3 = Many (~101 to 1000 houses)
#'   4 = Very Many (~1001 or more houses)
#'   }
#'   \item{HOUSES_DAMAGED}{Total Number of Houses Damaged by the Earthquake.}
#'   \item{HOUSES_DAMAGED_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 houses)
#'   2 = Some (~51 to 100 houses)
#'   3 = Many (~101 to 1000 houses)
#'   4 = Very Many (~1001 or more houses)
#'   }
#'   \item{TOTAL_DEATHS}{Total Number of Deaths from the Earthquake and secondary effects (eg Tsunami)}
#'   \item{TOTAL_DEATHS_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 deaths)
#'   2 = Some (~51 to 100 deaths)
#'   3 = Many (~101 to 1000 deaths)
#'   4 = Very Many (~1001 or more deaths)
#'   }
#'   \item{TOTAL_MISSING}{Total Number of Missing from the Earthquake and secondary effects (eg Tsunami)}
#'   \item{TOTAL_MISSING_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 missing)
#'   2 = Some(~51 to 100 missing)
#'   3 = Many (~101 to 1000 missing)
#'   4 = Very Many (~1001 or more missing)
#'   }
#'   \item{TOTAL_INJURIES}{Total Number of Injuries from the Earthquake and secondary effects (eg Tsunami)}
#'   \item{TOTAL_INJURIES_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 injuries)
#'   2 = Some(~51 to 100 injuries)
#'   3 = Many (~101 to 1000 injuries)
#'   4 = Very Many (~1001 or more injuries)
#'   }
#'   \item{TOTAL_DAMAGE_MILLIONS_DOLLARS}{Total Damage in Millions of Dollars from the Earthquake and secondary effects (eg Tsunami)}
#'   \item{TOTAL_DAMAGE_DESCRIPTION}{
#'   0 = NONE
#'   1 = LIMITED (roughly corresponding to less than $1 million)
#'   2 = MODERATE (~$1 to $5 million)
#'   3 = SEVERE (~>$5 to $24 million)
#'   4 = EXTREME (~$25 million or more)
#'   }
#'   \item{TOTAL_HOUSES_DESTROYED}{Total Number of Houses Destroyed by the Earthquake and secondary effects (eg Tsunami)}
#'   \item{TOTAL_HOUSES_DESTROYED_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 houses)
#'   2 = Some (~51 to 100 houses)
#'   3 = Many (~101 to 1000 houses)
#'   4 = Very Many (~1001 or more houses)
#'   }
#'   \item{TOTAL_HOUSES_DAMAGED}{Total Number of Houses Damaged by the Earthquake and secondary effects (eg Tsunami)}
#'   \item{TOTAL_HOUSES_DAMAGED_DESCRIPTION}{
#'   0 = None
#'   1 = Few (~1 to 50 houses)
#'   2 = Some (~51 to 100 houses)
#'   3 = Many (~101 to 1000 houses)
#'   4 = Very Many (~1001 or more houses)
#'   }
#'  }
#' @examples
#'  \dontrun{
#'  raw_df
#'  }
"raw_df"
